baseURL = 'https://adventures-preschool.netlify.app/'
languageCode = 'en-us'
title = 'Adventures Preschool'
theme = 'ananke'

[params]
  site_logo = ""
  description = "A nurturing preschool community"
  favicon = ""
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Programs"
    url = "/programs/"
    weight = 3
  [[menu.main]]
    name = "Admissions"
    url = "/admissions/"
    weight = 4
  [[menu.main]]
    name = "Staff"
    url = "/staff/"
    weight = 5
  [[menu.main]]
    name = "Calendar"
    url = "/calendar/"
    weight = 6
  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 7
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 8
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 9
